[package]
name = "rustemon"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
publish = true

[[example]]
name = "toml_serialize"
required-features = ["serialize"]

[[example]]
name = "check_static_resources"
required-features = ["static-resources"]

[[example]]
name = "custom_filesystem_client"
required-features = ["cache"]

[[example]]
name = "custom_in_memory_client"
required-features = ["cache"]

[dependencies]
reqwest = { version = "0.12.28", default-features = false, features = [
  "json",
  "rustls-tls-native-roots"
] }
reqwest-middleware = "0.4.2"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, optional = true }
thiserror = "2.0.19"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
toml = "0.9.8"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
http-cache-reqwest = { version = "0.16.0", features = ["manager-moka"] }

[features]
serialize = []
static-resources = ["dep:serde_json"]
